[project]
name = "jsonrpc"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
	"json-rpc",
	"werkzeug",
	"requests",
]
[tool.pyright]
reportMissingTypeStubs = false
reportUnknownMemberType = false
